module.exports = {
   "sven":"sven",
   "axe":"axe",
   "outworld devourer":"outworld devourer",
   "od":"outworld devourer",
   "o d":"outworld devourer",
   "invoker":"invoker",
   "rubick":"rubick",
   "faceless void":"faceless void",
   "void":"faceless void",
   "shadow demon":"shadow demon",
   "s d":"shadow demon",
   "phoenix":"phoenix",
   "elder titan":"elder titan",
   "et":"elder titan",
   "e t":"elder titan",
   "disruptor":"disruptor",
   "io":"io",
   "wisp":"io",
   "i o":"io",
   "bloodseeker":"bloodseeker",
   "blood seeker":"bloodseeker",
   "spectre":"spectre",
   "puck":"puck",
   "arc warden":"arc warden",
   "aw":"arc warden",
   "a w":"arc warden",
   "winter wyvern":"winter wyvern",
   "wyvern":"winter wyvern",
   "ww":"winter wyvern",
   "w w":"winter wyvern",
   "ember spirit":"ember spirit",
   "ember":"ember spirit",
   "tiny":"tiny",
   "dark seer":"dark seer",
   "ds":"dark seer",
   "d s":"dark seer",
   "underlord":"underlord",
   "under lord":"underlord",
   "pitlord":"underlord",
   "pit lord":"underlord",
   "bristleback":"bristleback",
   "bristle back":"bristleback",
   "bristle":"bristleback",
   "broodmother":"broodmother",
   "brood mother":"broodmother",
   "brood":"broodmother",
   "keeper of the light":"keeper of the light",
   "earth spirit":"earth spirit",
   "dragon knight":"dragon knight",
   "dk":"dragon knight",
   "d k":"dragon knight",
   "doom":"doom",
   "doombringer":"doom",
   "doom bringer":"doom",
   "queen of pain":"queen of pain",
   "qop":"queen of pain",
   "quwop":"queen of pain",
   "oracle":"oracle",
   "necropho":"necrophos",
   "necro":"necrophos",
   "tinker":"tinker",
   "beastmaster":"beastmaster",
   "beast master":"beastmaster",
   "beast":"beastmaster",
   "enigma":"enigma",
   "kunkka":"kunkka",
   "admiral kunkka":"kunkka",
   "lone druid":"lone druid",
   "ld":"lone druid",
   "l d":"lone druid",
   "windranger":"windranger",
   "wind ranger":"windranger",
   "windrunner":"windranger",
   "wind runner":"windranger",
   "luna":"luna",
   "natures prophet":"natures prophet",
   "nature's prophet":"natures prophet",
   "np":"natures prophet",
   "n p":"natures prophet",
   "clinkz":"clinkz",
   "clinks":"clinkz",
   "morphling":"morphling",
   "morph":"morphling",
   "medusa":"medusa",
   "ancient apparition":"ancient apparition",
   "aa":"ancient apparition",
   "a a":"ancient apparition",
   "slardar":"slardar",
   "treant protector":"treant protector",
   "treant":"treant protector",
   "tree ent":"treant protector",
   "tree ant":"treant protector",
   "shadow fiend":"shadow fiend",
   "sf":"shadow fiend",
   "s f":"shadow fiend",
   "lifestealer":"lifestealer",
   "life stealer":"lifestealer",
   "lycan":"lycan",
   "bounty hunter":"bounty hunter",
   "bh":"bounty hunter",
   "b h":"bounty hunter",
   "pugna":"pugna",
   "weaver":"weaver",
   "brewmaster":"brewmaster",
   "brew master":"brewmaster",
   "brew":"brewmaster",
   "silencer":"silencer",
   "tidehunter":"tidehunter",
   "tide hunter":"tidehunter",
   "lina":"lina",
   "slayer":"lina",
   "tusk":"tusk",
   "tuskar":"tusk",
   "tusker":"tusk",
   "ogre magi":"ogre magi",
   "ogre mcgee":"ogre magi",
   "clockwerk":"clockwerk",
   "clock werk":"clockwerk",
   "abaddon":"abaddon",
   "timbersaw":"timbersaw",
   "timber saw":"timbersaw",
   "pudge":"pudge",
   "viper":"viper",
   "skywrath mage":"skywrath mage",
   "sky wrath mage":"skywrath mage",
   "sky wraith mage":"skywrath mage",
   "terrorblade":"terrorblade",
   "terror blade":"terrorblade",
   "tb":"terrorblade",
   "t b":"terrorblade",
   "venomancer":"venomancer",
   "veno mancer":"venomancer",
   "veno":"venomancer",
   "phantom assassin":"phantom assassin",
   "pa":"phantom assassin",
   "p a":"phantom assassin",
   "centaur warrunner":"centaur warrunner",
   "centaur war runner":"centaur warrunner",
   "centaur":"centaur warrunner",
   "phantom lancer":"phantom lancer",
   "pl":"phantom lancer",
   "p l":"phantom lancer",
   "lancer":"phantom lancer",
   "lich":"lich",
   "visage":"visage",
   "bane":"bane",
   "witch doctor":"witch doctor",
   "doctor":"witch doctor",
   "wd":"witch doctor",
   "w d":"witch doctor",
   "earthshaker":"earthshaker",
   "earth shaker":"earthshaker",
   "shaker":"earthshaker",
   "storm spirit":"storm spirit",
   "storm":"storm spirit",
   "s s":"storm spirit",
   "anti-mage":"anti-mage",
   "anti mage":"anti-mage",
   "am":"anti-mage",
   "a m":"anti-mage",
   "batrider":"batrider",
   "bat rider":"batrider",
   "bat":"batrider",
   "rider":"batrider",
   "vengeful spirit":"vengeful spirit",
   "vengeful":"vengeful spirit",
   "venge":"vengeful spirit",
   "vengance":"vengeful spirit",
   "venge":"vengeful spirit",
   "eventful":"vengeful spirit",
   "razor":"razor",
   "drow ranger":"drow ranger",
   "drow":"drow ranger",
   "juggernaut":"juggernaut",
   "jugg":"juggernaut",
   "wraith king":"wraith king",
   "wraith":"wraith king",
   "skeleton king":"wraith king",
   "nyx assassin":"nyx assassin",
   "nyx":"nyx assassin",
   "nix":"nyx assassin",
   "nick":"nyx assassin",
   "nicks":"nyx assassin",
   "techie":"techies",
   "ursa":"ursa",
   "ursabear":"ursa",
   "ursa bear":"ursa",
   "alchemist":"alchemist",
   "alch":"alchemist",
   "alk":"alchemist",
   "templar assassin":"templar assassin",
   "templar":"templar assassin",
   "ta":"templar assassin",
   "t a":"templar assassin",
   "chen":"chen",
   "gyrocopter":"gyrocopter",
   "gyro":"gyrocopter",
   "slark":"slark",
   "mirana":"mirana",
   "potam":"mirana",
   "pot am":"mirana",
   "zeu":"zeus",
   "legion commander":"legion commander",
   "legion":"legion commander",
   "commander":"legion commander",
   "naga siren":"naga siren",
   "naga":"naga siren",
   "siren":"naga siren",
   "dazzle":"dazzle",
   "shadow shaman":"shadow shaman",
   "rasta":"shadow shaman",
   "death prophet":"death prophet",
   "dp":"death prophet",
   "d p":"death prophet",
   "enchantres":"enchantress",
   "enchant":"enchantress",
   "sand king":"sand king",
   "s k":"sand king",
   "night stalker":"night stalker",
   "stalker":"night stalker",
   "ns":"night stalker",
   "n s":"night stalker",
   "huskar":"huskar",
   "riki":"riki",
   "rikimaru":"riki",
   "spirit breaker":"spirit breaker",
   "breaker":"spirit breaker",
   "leshrac":"leshrac",
   "leshrack":"leshrac",
   "leshrak":"leshrac",
   "jakiro":"jakiro",
   "omniknight":"omniknight",
   "omni knight":"omniknight",
   "omni":"omniknight",
   "chaos knight":"chaos knight",
   "chaos":"chaos knight",
   "ck":"chaos knight",
   "c k":"chaos knight",
   "troll warlord":"troll warlord",
   "troll war lord":"troll warlord",
   "troll":"troll warlord",
   "meepo":"meepo",
   "meapo":"meepo",
   "lion":"lion",
   "undying":"undying",
   "warlock":"warlock",
   "war lock":"warlock",
   "sniper":"sniper",
   "crystal maiden":"crystal maiden",
   "crystal":"crystal maiden",
   "maiden":"crystal maiden",
   "cm":"crystal maiden",
   "c m":"crystal maiden",
   "rylai":"crystal maiden",
   "magnu":"magnus",
   "mag":"magnus",
   "magnataur":"magnus"
};
